import {parseRuleText} from '../semantic/registry.js';
import fs from 'node:fs';import assert from 'node:assert/strict';
import {RwaQaEngine} from '../rwa_engine.js';
import {parseCsv,expandCsvRows} from '../csv_adapter.js';import {tableauRowToClient} from '../tableau_adapter.js';
const WEB=new URL('../',import.meta.url),read=n=>fs.readFileSync(new URL(n,WEB),'utf8');
const cfg=JSON.parse(read('tableau_config.txt')),cat=JSON.parse(read('rwa_sample_data.txt')).groups,rules=JSON.parse(read('rules_config.txt')),reg=parseRuleText(read('command_patterns.txt'));
const clients=parseCsv(read('tableau_sample.csv')).map(r=>tableauRowToClient(r,cat.find(g=>g.client_group_id===r.client_group_id),cfg.fields));const data=expandCsvRows(clients);const options={...data,entityAliases:{...data.entityAliases,...rules.entityAliases},commandPatterns:reg,portfolioComplete:true};
const spec=JSON.parse(fs.readFileSync(new URL('dialogue_application_cases.json',import.meta.url),'utf8'));let pass=0,fail=0;const results=[];
function periodKey(p){if(!p)return null;if(p.mode==='month')return p.month;if(p.mode==='comparison')return p.months;return p.mode;}
function check(r,e){if(!r.ok)return 'not ok: '+r.answer;const p=r.plan;if(p.action!==e.action)return `action ${p.action}`;for(const k of ['group','entity','driver','metric','direction','topN'])if(e[k]!==undefined&&p[k]!==e[k])return `${k} ${p[k]}`;if(e.period&&periodKey(p.period)!==e.period)return `period ${JSON.stringify(p.period)}`;if(e.comparison&&JSON.stringify(p.period?.months)!==JSON.stringify(e.comparison))return `comparison ${JSON.stringify(p.period)}`;if(e.excludedDrivers&&JSON.stringify(p.excludedDrivers)!==JSON.stringify(e.excludedDrivers))return `excluded ${JSON.stringify(p.excludedDrivers)}`;if(e.candidateCount!==undefined&&(p.candidateEntities?.length||0)!==e.candidateCount)return `candidateCount ${p.candidateEntities?.length||0}`;return null;}
for(const c of spec.conversations){const eng=new RwaQaEngine(data.rows,options);for(let i=0;i<c.turns.length;i++){const t=c.turns[i],r=eng.answer(t.question,c.context),err=check(r,t.expected);results.push({id:c.id,turn:i+1,question:t.question,ok:!err,error:err,plan:r.plan||null,answer:r.answer});if(err){fail++;console.error(c.id,i+1,t.question,err)}else pass++;}}
for(const a of spec.applications){const eng=new RwaQaEngine(data.rows,options),r=eng.answer(a.question,a.context),err=check(r,a.expected);results.push({id:a.id,question:a.question,ok:!err,error:err,plan:r.plan||null,answer:r.answer});if(err){fail++;console.error(a.id,a.question,err)}else pass++;}
const report={suite:'v3 dialogue/application regression; developer-authored, not independent validation',passed:pass,failed:fail,results};fs.writeFileSync(new URL('../reports/dialogue_application_regression.json',import.meta.url),JSON.stringify(report,null,2));console.log({passed:pass,failed:fail});if(fail)process.exitCode=1;
