import assert from 'node:assert/strict';
import fs from 'node:fs';
import {RwaQaEngine} from '../rwa_engine.js';
import {parseRuleText} from '../semantic/registry.js';
import {indexRowsToCatalog,nameVariants} from '../group_catalog.js';
import {planDataRequest} from '../semantic/routing.js';
const reg=parseRuleText(fs.readFileSync('command_patterns.txt','utf8'));
const checks=[];
function test(name,f){try{f();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.stack});}}
const mk=(gid,name,month,prev,curr,derived=false,eid='E1')=>({client_group_id:gid,client_group:name,entity_id:eid,entity:name+' Subsidiary',month,rwa_prev:prev,rwa_curr:curr,drivers:{EAD:curr-prev},...(derived?{attributes:{rwa_prev_source:'derived_from_current_rwa_minus_deduplicated_driver_impacts'}}:{})});
const rows=[mk('0001','ALPHA GROUP','2026-05',100,150),mk('0001','ALPHA GROUP','2026-06',150,120),mk('0001','ALPHA GROUP','2026-07',120,132),mk('0002','BETA GROUP','2026-05',100,120),mk('0002','BETA GROUP','2026-06',120,168),mk('0002','BETA GROUP','2026-07',168,159.6)];
function eng(rr=rows,options={}){const cat=indexRowsToCatalog(rr.map(r=>({client_group_id:r.client_group_id,client_group_name:r.client_group})));return new RwaQaEngine(rr,{commandPatterns:reg,semanticCatalog:cat,portfolioComplete:true,...options});}
const high='Show top 10 groups by highest monthly percentage change over all history';
const low='Show top 10 groups by lowest monthly percentage change over all history';
const context={selectedMonth:'2026-07'};
function run(q=high,rr=rows,options={}){const r=eng(rr,options).answer(q,context);assert.equal(r.ok,true,r.answer);return r;}
test('High selects max monthly %, not cumulative amount',()=>{const r=run();assert.deepEqual(r.result.items.map(x=>x.groupId),['0001','0002']);assert.equal(r.result.items[0].month,'2026-05');assert.equal(r.result.items[0].change,50);assert.equal(r.result.items[1].month,'2026-06');assert.equal(r.result.items[1].change,48);});
test('Low includes negative percentage, ascending',()=>{const r=run(low);assert.equal(r.result.items[0].groupId,'0001');assert.equal(r.result.items[0].month,'2026-06');assert.equal(r.result.items[0].change,-30);assert.ok(Math.abs(r.result.items[1].rate+.05)<1e-12);});
test('High has each group only once with month, amount, percentage',()=>{const r=run();assert.equal(r.result.items.length,2);assert.equal(new Set(r.result.items.map(x=>x.groupId)).size,2);assert.ok(r.table.columns.includes('Peak month'));assert.match(r.answer,/Group ID: 0001/);});
test('Lowest is signed, not absolute magnitude',()=>{const rr=[mk('a','Alpha','2026-07',100,95),mk('b','Beta','2026-07',100,60)];assert.equal(run(low,rr).result.items[0].groupId,'b');});
test('Observed adjacent month takes precedence over derived prev',()=>{const rr=[mk('a','Alpha','2026-06',-10,100,true),mk('a','Alpha','2026-07',-100,200,true)];const r=run(high,rr);assert.equal(r.result.items[0].rate,1);assert.equal(r.result.items[0].change,100);assert.equal(r.result.items[0].previousBasis,'observed prior-month closing');assert.equal(r.result.skippedByReason.NO_OBSERVED_PREVIOUS,1);});
test('All derived and no observed preceding month => no invented percentage',()=>{const r=run(high,[mk('a','Alpha','2026-07',50,100,true)]);assert.equal(r.result.items.length,0);assert.equal(r.result.skippedByReason.NO_OBSERVED_PREVIOUS,1);});
test('Zero denominator is excluded, not infinite',()=>{const r=run(high,[mk('a','Alpha','2026-07',0,100)]);assert.equal(r.result.items.length,0);assert.equal(r.result.skippedByReason.NON_POSITIVE_PREVIOUS,1);});
test('Explicitly supplied positive reported previous is accepted',()=>{const r=run(high,[mk('a','Alpha','2026-07',100,120)]);assert.equal(r.result.items[0].rate,.2);assert.equal(r.result.items[0].previousBasis,'explicitly reported previous');});
test('Missing current month is unknown, not zero',()=>{const rr=[...rows,mk('c','Gamma','2026-07',100,150)];const r=run(high,rr);assert.equal(r.result.skippedByReason.NO_CURRENT_MONTH,2);assert.match(r.answer,/eligible observed months only/);});
test('One month with no valid basis does not silently become zero',()=>{const rr=[mk('a','Alpha','2026-05',0,100),mk('a','Alpha','2026-07',80,100,true)];const r=run(high,rr);assert.equal(r.result.eligible,0);assert.equal(r.result.skippedByReason.NO_OBSERVED_PREVIOUS,1);});
test('Explicit window still uses preceding month outside window',()=>{const rr=[mk('a','Alpha','2026-05',10,100,true),mk('a','Alpha','2026-06',50,120,true)];const r=eng(rr).answer('Show top 10 groups by highest monthly percentage change in June',{selectedMonth:'2026-06'});assert.ok(r.ok,r.answer);assert.equal(r.result.items[0].rate,.2);});
test('Ratio based on aggregate group, not mean of entity ratios',()=>{const rr=[mk('a','Alpha','2026-07',100,200,false,'e1'),mk('a','Alpha','2026-07',900,900,false,'e2')];const r=run(high,rr);assert.equal(r.result.items[0].rate,.1);assert.equal(r.result.items[0].change,100);});
test('Duplicate group names do not collapse IDs',()=>{const rr=rows.map(r=>({...r,client_group:'Shared'}));const r=run(high,rr);assert.equal(r.result.items.length,2);assert.deepEqual(r.result.items.map(x=>x.id),['0001','0002']);});
test('Equal peak percentage selects latest month and retains ties',()=>{const rr=[mk('a','Alpha','2026-06',100,150),mk('a','Alpha','2026-07',150,225)];const r=run(high,rr);assert.equal(r.result.items[0].month,'2026-07');assert.deepEqual(r.result.items[0].tiedMonths,['2026-07','2026-06']);});
test('Cross-group ties have stable ID order/rank',()=>{const rr=[mk('02','X','2026-07',100,120),mk('01','Y','2026-07',100,120)];const r=run(high,rr);assert.deepEqual(r.result.items.map(x=>[x.id,x.rank]),[['01',1],['02',1]]);});
test('Input order does not change extrema',()=>{const a=run(),b=run(high,[...rows].reverse());assert.deepEqual(a.result.items.map(x=>[x.id,x.month,x.value,x.change]),b.result.items.map(x=>[x.id,x.month,x.value,x.change]));});
test('Does not include data after context end',()=>{const rr=[...rows,mk('a','Future','2026-08',1,1000)];const r=run(high,rr);assert.ok(r.result.items.every(x=>x.month<='2026-07'));});
test('Unauthorised / incomplete portfolio cannot run',()=>{const r=eng(rows,{portfolioComplete:false}).answer(high,context);assert.equal(r.ok,false);assert.match(r.answer,/fresh complete authorised/);});
test('Output ID remains a string preserving zeros',()=>{const r=run();assert.equal(typeof r.table.rows[0][1],'string');assert.equal(r.table.rows[0][1],'0001');});
test('Group exclusion removes only named ID',()=>{const r=run(high+' excluding 0001');assert.deepEqual(r.result.items.map(x=>x.id),['0002']);});
test('Balance discrepancy is visible, no silent source switch',()=>{const rr=[mk('a','Alpha','2026-06',10,100),mk('a','Alpha','2026-07',50,120)];const r=run(high,rr);assert.equal(r.result.openingDisagreements,1);assert.ok(r.warnings.some(w=>w.includes('differ from')));});
const rejects=[high+' excluding FX',high+' above 25 million',high+' by EAD',high+' excluding an imaginary entity',high+' in July',high+' by absolute value',high+' by total RWA balance',high.replace('groups','entities'),high+' and lowest monthly percentage change','Predict groups by highest monthly percentage change next year','Compare groups by highest monthly percentage change in June and July'];
for(const q of rejects)test('Reject incompatible request: '+q,()=>{const r=eng().parseQuestion(q,context);assert.equal(r.ok,false,JSON.stringify(r.plan));});
for(const q of [high,low,'Top 5 groups by peak RWA increase over all history','Top 5 groups by peak percentage increase','Top 5 groups by lowest monthly percentage increase from May to July'])test('Parser/routing: '+q,()=>{const e=eng();const parsed=e.parseQuestion(q,context);assert.ok(parsed.ok,parsed.message);assert.equal(parsed.plan.action,'HISTORICAL_GROUP_PEAK');const rr=planDataRequest(q,e.options.semanticCatalog,reg,{},context);assert.ok(rr.ok,rr.message);assert.ok(rr.portfolio);});
test('Successful repeat retains extrema action',()=>{const e=eng();const r=e.answer(high,context);assert.ok(r.ok);const next=e.answer('Again',context);assert.ok(next.ok,next.answer);assert.equal(next.plan.action,'HISTORICAL_GROUP_PEAK');});
test('Unsupported reference does not turn into a different financial report',()=>{const e=eng();e.answer(high,context);const r=e.answer('Explain the first one',context);assert.equal(r.ok,false);assert.ok(['UNSUPPORTED_CONTEXT','MISSING_REQUIRED_SLOT'].includes(r.code));});
test('Ordinary ranking keeps monetary amounts unchanged',()=>{const r=run('Top 10 groups by RWA increase in July');assert.equal(r.plan.action,'TOP_CLIENTS');assert.equal(r.result.items[0].change,12);});
test('Ordinary negative basis moves to notes; diagnostics retained',()=>{const r=run('Top 10 groups by RWA increase in July',[mk('a','Alpha','2026-07',-5,10,true)]);assert.ok(!r.answer.includes('A negative derived'));assert.ok(r.warnings.some(w=>w.startsWith('A negative derived')));assert.ok(r.detailNotes.some(w=>w.startsWith('A negative derived')));});
test('Existing percentage report keeps basis warning visible',()=>{const r=run('Top 10 groups by percentage increase in July',[mk('a','Alpha','2026-07',-5,10,true,'e1'),mk('a','Alpha','2026-07',105,110,true,'e2')]);assert.ok(r.answer.includes('A negative derived'));});
fs.mkdirSync('reports/chat_ux',{recursive:true});
fs.writeFileSync('reports/chat_ux/peak_checks.json',JSON.stringify({passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks},null,2));
for(const c of checks.filter(x=>!x.passed))console.error(c.name,c.error);
console.log(checks.filter(x=>x.passed).length+'/'+checks.length);
if(checks.some(x=>!x.passed))process.exitCode=1;
