/** Verify no command changes on exact/clean control queries, with identical contexts. */
import fs from 'node:fs';import path from 'node:path';
import {ROOT,loadFixtures,actualFields,metrics} from './evaluate.mjs';
import {parseCsv} from '../csv_adapter.js';import {parseRuleText} from '../semantic/registry.js';import {RwaQaEngine} from '../rwa_engine.js';
const data=loadFixtures(),reg=parseRuleText(fs.readFileSync(path.join(ROOT,'command_patterns.txt'),'utf8')),catalog=JSON.parse(fs.readFileSync(path.join(ROOT,'rwa_sample_data.txt'),'utf8'));
const make=disabled=>new RwaQaEngine(data.rows,{...data,commandPatterns:reg,semanticCatalog:catalog,portfolioComplete:true,disableFuzzy:disabled});
const enabled=make(false),disabled=make(true),results=[];
const extra=parseCsv(fs.readFileSync(path.join(ROOT,'tests/robustness.csv'),'utf8'));
const typoConversations=new Set(extra.filter(c=>c.expected_status==='ACCEPT'&&c.category.includes('TYPO')).map(c=>c.conversation_id));
const sets=[['legacy',parseCsv(fs.readFileSync(path.join(ROOT,'tests/questions.csv'),'utf8'))],['clean',extra.filter(c=>!typoConversations.has(c.conversation_id))]];
for(const [label,cases] of sets){let conv=null;for(const c of cases){if(c.conversation_id!==conv){enabled.reset();disabled.reset();conv=c.conversation_id;}const ctx={selectedClientGroup:c.context_group||undefined,selectedEntity:c.context_entity||undefined,selectedMonth:c.context_month||undefined};const a=enabled.parseQuestion(c.question,ctx),b=disabled.parseQuestion(c.question,ctx);let same=a.ok===b.ok;if(a.ok&&b.ok)same=JSON.stringify(actualFields(a.plan))===JSON.stringify(actualFields(b.plan));const pass=(c.expected_status==='ACCEPT'?same:!a.ok&&!b.ok);if(a.ok)enabled.answer(c.question,ctx);if(b.ok)disabled.answer(c.question,ctx);results.push({id:c.id,set:label,question:c.question,statusExpected:c.expected_status,passed:pass,onAccepted:a.ok,offAccepted:b.ok,codeOn:a.code||'ACCEPT',codeOff:b.code||'ACCEPT'});}}
const report={excludedPositiveTypoConversations:[...typoConversations],suite:'Fuzzy ON vs OFF clean/negative controls; not representative external accuracy',total:results.length,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,definition:'Accepted clean commands must have identical full canonical plans; hard negatives must be rejected by both. Error reason text may differ. Financial execution uses the same unchanged functions.',results};fs.writeFileSync(path.join(ROOT,'reports/fuzzy_clean_comparison.json'),JSON.stringify(report,null,2));console.log({total:report.total,passed:report.passed,failed:report.failed});if(report.failed){console.log(results.filter(x=>!x.passed));process.exitCode=1;}
