from pathlib import Path
import json, sys, time, shutil
sys.path.insert(0,str(Path(__file__).resolve().parent))
from dom_fixture import make_html
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
REPORT=ROOT/'local_manager_reports';REPORT.mkdir(exist_ok=True)
checks=[]
def mark(name,ok=True,detail=None):
 checks.append({'name':name,'passed':bool(ok),'detail':detail})
 if not ok: raise AssertionError(name+': '+str(detail))
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True, executable_path=shutil.which("chromium") or None)
 page=browser.new_page(viewport={'width':1512,'height':1100},device_scale_factor=1)
 errors=[];requests=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url))
 page.on('dialog',lambda d:d.accept())
 try:
  page.set_content(make_html())
  mark('Isolated DOM uses real JS modules and precomputed compiler fixtures')
  page.wait_for_function("() => document.querySelector('#notice').textContent.includes('Ready.')",timeout=15000)
  mark('Original engine modules loaded',not errors,errors)
  mark('Seven CSV sources; no customer master editing',page.locator('#file-nav .nav-item').count()==7)
  page.screenshot(path=str(REPORT/'01_editor.png'),full_page=True)
  page.click('#tab-test');page.select_option('#test-source','saved')
  page.fill('#question',"Take me through Samsung's RWA movement in July.")
  page.click('#parse');page.wait_for_function("() => !document.body.classList.contains('busy')")
  before=page.locator('#parse-badge').inner_text();mark('Unregistered expression initially rejected','ACCEPT' not in before,before)
  page.click('#tab-edit');page.click('#add-row');page.select_option('#field-concept','ROOT')
  page.fill('#field-phrase','take me through');page.fill('#field-notes','Browser smoke-test expression')
  page.click('#edit-form button[type=submit]');mark('Draft-only row add',page.locator('#dirty-badge').inner_text().startswith('1 file(s)'))
  page.click('#validate');page.wait_for_function("() => !document.body.classList.contains('busy')",timeout=40000)
  mark('Existing compiler validates draft','Validation passed' in page.locator('#build-status').inner_text(),page.locator('#notice').inner_text())
  page.click('#tab-test');page.select_option('#test-source','draft');page.fill('#question',"Take me through Samsung's RWA movement in July.")
  page.click('#parse');page.wait_for_function("() => !document.body.classList.contains('busy')",timeout=30000)
  mark('Edited phrase reaches original engine','ACCEPT' in page.locator('#parse-badge').inner_text(),page.locator('#parse-message').inner_text())
  mark('Correct group and month','SAMSUNG GROUP' in page.locator('#plan-grid').inner_text() and '2026-07' in page.locator('#plan-grid').inner_text())
  mark('Parse alone does not commit conversation',page.locator('#test-state').text_content()=='{}')
  page.click('#execute');mark('Sample calculation commits state','GROUP_ROOT_CAUSE' in page.locator('#test-state').text_content(),page.locator('#sample-answer').inner_text())
  page.fill('#question','How about Toyota?');page.click('#parse');page.wait_for_function("() => !document.body.classList.contains('busy')")
  mark('Follow-up changes group and keeps July','TOYOTA GROUP' in page.locator('#plan-grid').inner_text() and '2026-07' in page.locator('#plan-grid').inner_text())
  page.click('#execute');mark('Fresh Toyota answer','TOYOTA' in page.locator('#sample-answer').inner_text())
  page.screenshot(path=str(REPORT/'02_question_test.png'),full_page=True)
  page.fill('#question','And August?');page.click('#parse');page.wait_for_function("() => !document.body.classList.contains('busy')")
  mark('Next period patch','2026-08' in page.locator('#plan-grid').inner_text())
  page.click('#execute');mark('Missing period does not commit','2026-08' not in json.dumps(json.loads(page.locator('#test-state').text_content()).get('period',{})),page.locator('#sample-answer').inner_text())
  page.click('#run-checks');page.wait_for_function("() => !document.body.classList.contains('busy')",timeout=45000)
  summary=page.locator('#checks-result').inner_text();mark('Twelve regression checks','12/12 PASS' in summary,summary)
  page.click('#save');page.wait_for_function("() => !document.body.classList.contains('busy')",timeout=40000)
  mark('Explicit local save','Save complete' in page.locator('#build-status').inner_text(),page.locator('#notice').inner_text())
  mark('Save button invokes commit API contract',page.evaluate('__RM_MOCK.state.commits===1'))
  page.click('#tab-backup');page.wait_for_selector('.backup-card')
  mark('Backup is visible',page.locator('.backup-card').count()>=1)
  page.screenshot(path=str(REPORT/'03_backups.png'),full_page=True)
  page.locator('.backup-card button').first.click();page.wait_for_function("() => !document.body.classList.contains('busy')",timeout=40000)
  mark('Restore recompiled source',page.evaluate("!__RM_MOCK.state.disk.tables['synonyms.csv'].rows.some(r=>r.phrase==='take me through')"))
  page.click('#tab-edit');page.fill('#search','what drove');mark('Search filters table',page.locator('#table-body tr').count()>0)
  page.locator('#table-body tr button').filter(has_text='Edit').first.click();page.select_option('#field-enabled','false');page.click('#edit-form button[type=submit]')
  mark('Disable via form','Disabled' in page.locator('#table-body').inner_text())
  page.click('#reload');page.wait_for_function("() => !document.body.classList.contains('busy')")
  # Test duplicate conflict and preservation. No saved files change.
  page.click('#add-row');page.select_option('#field-concept','DECREASE');page.fill('#field-phrase','increase');page.click('#edit-form button[type=submit]')
  page.click('#validate');page.wait_for_function("() => !document.body.classList.contains('busy')",timeout=40000)
  mark('Conflict shown and save disabled','Validation failed' in page.locator('#build-status').inner_text() and page.locator('#save').is_disabled())
  page.click('#reload');page.wait_for_function("() => !document.body.classList.contains('busy')")
  page.set_viewport_size({'width':430,'height':932});page.screenshot(path=str(REPORT/'04_mobile.png'),full_page=True)
  mark('Mobile document has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
  mark('No JS errors',not errors,errors)
  external=[u for u in requests if not u.startswith('http://127.0.0.1:8765/')]
  mark('No network requests in the isolated fixture',not external,external)
 finally:
  (REPORT/'browser_dom.json').write_text(json.dumps({'kind':'Isolated Chromium DOM. Real engine/manager JS; mocked fetch/API with precomputed real compiler fixtures. Actual browser HTTP blocked by administrator; Python HTTP tested separately.','checks':checks,'passed':sum(x['passed'] for x in checks),'errors':errors},ensure_ascii=False,indent=2))
  browser.close()
print(json.dumps({'passed':sum(x['passed'] for x in checks),'total':len(checks)},ensure_ascii=False))
