import {TestLab} from './test_lab.js';
const $=id=>document.getElementById(id),copy=x=>JSON.parse(JSON.stringify(x));
const S={base:null,tables:null,metadata:null,choices:null,token:'',file:'synonyms.csv',page:0,pageSize:35,epoch:0,draft:null,busy:false,tab:'edit',edit:null,lab:new TestLab(),customChecks:null};
const DISPLAY_ORDER=['synonyms.csv','followups.csv','commands.csv','fuzzy_config.csv','units.csv','temporal.csv','settings.csv'];
const LABELS={concept:'Canonical concept',phrase:'Expression / phrase',weight:'Manual match strength',enabled:'Enabled',notes:'Notes',rule_id:'Rule ID',pattern:'Follow-up pattern',patch_type:'Context patch',target_slot:'Target slot',command_id:'Command ID',kind:'Type',canonical_id:'Data ID',canonical_name:'Canonical name',parent_id:'Parent group ID',alias:'Alias',action:'Execution function',grammar:'Grammar ID',response_template:'Existing response function',scope:'Analysis scope',primary_features:'Primary features (separate with |)',supporting_features:'Supporting features (separate with |)',contradiction_features:'Contradiction features (separate with |)',required_slots:'Required slots (separate with |)',optional_slots:'Optional slots (separate with |)',forbidden_slots:'Forbidden slots (separate with |)',min_confidence:'Minimum rule fit',min_margin:'Minimum candidate margin',category:'Recovery category',min_length:'Minimum length',threshold:'Similarity threshold',max_edits:'Maximum edit distance',max_corrections:'Maximum corrections',multiplier:'Fixed multiplier',value:'Value',key:'Setting key'};
function note(text,type=''){const el=$('notice');el.textContent=text;el.className='notice'+(type?' '+type:'');}
function busy(on){S.busy=on;document.body.classList.toggle('busy',on);updateActions();}
function handleError(e){note(e.message||String(e),'error');if(e.file){S.file=e.file;S.page=Math.max(0,Math.floor(((e.line||2)-2)/S.pageSize));render();}if(e.code==='COMPILER_VALIDATION'){$('build-log').textContent=e.message;$('build-details').open=true;$('build-status').textContent='Validation failed · Source files were not changed.';}}
async function api(path,payload){const opt={cache:'no-store',headers:{'X-RWA-CSRF':S.token}};if(payload!==undefined){opt.method='POST';opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(payload);}const r=await fetch('/api/'+path,opt);let data;try{data=await r.json();}catch{throw Error('Could not read the local server response. Check that the Python server is running.');}if(!r.ok){const e=Object.assign(new Error(data.message||'Request failed.'),data);throw e;}return data;}
function changedFiles(){if(!S.base)return[];return DISPLAY_ORDER.filter(n=>JSON.stringify(S.tables[n].rows)!==JSON.stringify(S.base.tables[n].rows));}
function updateActions(){const changed=changedFiles();$('save').disabled=S.busy||!S.draft||S.draft.epoch!==S.epoch;$('dirty-badge').textContent=changed.length?`${changed.length} file(s) · Unsaved`:'Saved version';$('dirty-badge').className='pill'+(changed.length?' dirty':'');$('changes-count').textContent=changed.length;}
function mutate(){S.epoch++;S.draft=null;S.lab.pending=null;$('execute').disabled=true;$('build-status').textContent='Draft changed. Source files have not been saved yet.';updateActions();renderCounts();}
function adopt(snapshot){S.base=copy(snapshot);S.tables=copy(snapshot.tables);S.draft=null;S.epoch++;S.lab.reset();$('execute').disabled=true;$('sample-answer').hidden=true;render();renderConversation();}
function setTab(tab){S.tab=tab;for(const n of ['edit','test','backup']){$('panel-'+n).hidden=n!==tab;$('tab-'+n).classList.toggle('active',n===tab);$('tab-'+n).setAttribute('aria-selected',String(n===tab));}if(tab==='backup')refreshBackups().catch(handleError);}
function renderCounts(){if(!S.tables)return;$('rule-count').textContent=Object.values(S.tables).reduce((n,t)=>n+t.rows.length,0).toLocaleString();$('artifact-status').textContent=S.base.artifactConsistent?'Matches CSVs':'Rebuild required';$('revision-label').textContent='revision '+S.base.revision.slice(0,12);}
function renderNav(){const nav=$('file-nav');nav.replaceChildren();for(const file of DISPLAY_ORDER){const btn=document.createElement('button');btn.className='nav-item'+(file===S.file?' active':'');const span=document.createElement('span');span.textContent=S.metadata[file].title;const count=document.createElement('small');count.textContent=S.tables[file].rows.length;btn.append(span,count);btn.onclick=()=>{S.file=file;S.page=0;$('search').value='';$('enabled-only').checked=false;setTab('edit');render();};nav.append(btn);}}
function filtered(){const q=$('search').value.toLowerCase();return S.tables[S.file].rows.map((r,i)=>({r,i})).filter(({r})=>(!$('enabled-only').checked||r.enabled===undefined||['true','1'].includes(r.enabled))&&(!q||Object.values(r).some(v=>v.toLowerCase().includes(q))));}
function renderTable(){const meta=S.metadata[S.file];$('file-title').textContent=meta.title;$('file-description').textContent=meta.description;$('file-path').textContent='rules/'+S.file;$('table-head').replaceChildren();const head=document.createElement('tr');for(const name of ['#',...meta.columns,'Actions']){const th=document.createElement('th');th.textContent=name;head.append(th);}$('table-head').append(head);const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/S.pageSize));S.page=Math.min(S.page,pages-1);$('table-body').replaceChildren();for(const{r,i}of rows.slice(S.page*S.pageSize,(S.page+1)*S.pageSize)){const tr=document.createElement('tr');if(r.enabled==='false'||r.enabled==='0')tr.className='disabled-row';const index=document.createElement('td');index.className='row-index';index.textContent=i+1;tr.append(index);for(const col of meta.columns){const td=document.createElement('td');if(col==='enabled'){const label=document.createElement('span');label.className=['true','1'].includes(r[col])?'state-on':'state-off';label.textContent=['true','1'].includes(r[col])?'Enabled':'Disabled';td.append(label);}else{td.textContent=r[col]||'—';if(['concept','command_id','canonical_id','rule_id','patch_type','category','key'].includes(col))td.className='mono';}tr.append(td);}const td=document.createElement('td'),actions=document.createElement('div');actions.className='row-actions';for(const[label,action]of [['Edit',()=>editRow(i)],['Duplicate',()=>editRow(i,true)],['Delete',()=>removeRow(i)]]){const b=document.createElement('button');b.className=label==='Delete'?'quiet danger':'quiet';b.textContent=label;b.onclick=action;actions.append(b);}td.append(actions);tr.append(td);$('table-body').append(tr);}$('page-summary').textContent=`${rows.length.toLocaleString()} matching / ${S.tables[S.file].rows.length.toLocaleString()} total rows`;$('page-label').textContent=`${S.page+1} / ${pages}`;$('previous').disabled=S.page===0;$('next').disabled=S.page>=pages-1;}
function render(){if(!S.tables)return;renderNav();renderTable();renderCounts();updateActions();}
function fieldChoices(key,file){if(key==='enabled')return['true','false'];if(key==='concept')return S.choices.concepts;if(key==='action'||key==='response_template')return S.choices.actions;if(key==='grammar')return S.choices.grammars;if(key==='patch_type')return S.choices.patches;if(key==='target_slot')return['',...S.choices.slots];if(key==='scope')return['ANY','GROUP','ENTITY','PORTFOLIO'];if(key==='kind')return file==='aliases.csv'?['GROUP','ENTITY']:file==='units.csv'?['absolute','ratio']:['MONTH','RELATIVE_MONTH','RELATIVE_QUARTER','YTD'];if(key==='category')return['semantic_word','entity','short_word'];return null;}
function defaults(file){const row=Object.fromEntries(S.tables[file].headers.map(k=>[k,'']));if('enabled'in row)row.enabled='true';if(file==='synonyms.csv')Object.assign(row,{concept:'ROOT',weight:'1'});if(file==='followups.csv')Object.assign(row,{rule_id:'CUSTOM_'+Date.now(),pattern:'how about {scope}',patch_type:'REPLACE_SCOPE',target_slot:'entity'});if(file==='aliases.csv')row.kind='GROUP';if(file==='commands.csv')Object.assign(row,copy(S.tables[file].rows[0]||{}),{command_id:'CUSTOM_'+Date.now()});return row;}
function editRow(index=null,duplicate=false){if(S.busy)return;const file=S.file;let row=index===null?defaults(file):copy(S.tables[file].rows[index]);if(duplicate){if(row.rule_id)row.rule_id='COPY_'+Date.now();if(row.command_id&&file==='commands.csv')row.command_id='COPY_'+Date.now();}S.edit={file,index:duplicate?null:index};$('edit-file').textContent='rules/'+file;$('edit-title').textContent=index===null?'Add rule':duplicate?'Duplicate rule':'Edit rule';$('edit-fields').replaceChildren();for(const key of S.tables[file].headers){const label=document.createElement('label');label.textContent=LABELS[key]||key;if(['notes','phrase','pattern','alias','canonical_name','required_slots','optional_slots','forbidden_slots','primary_features','supporting_features','contradiction_features'].includes(key))label.className='wide';const choices=fieldChoices(key,file);let field;if(choices){field=document.createElement('select');for(const choice of choices){const o=new Option(choice||'(None)',choice);field.add(o);}if(!choices.includes(row[key]))field.add(new Option(row[key],row[key]));}else if(key==='notes'||key.endsWith('_features')||key.endsWith('_slots')){field=document.createElement('textarea');field.rows=2;}else{field=document.createElement('input');field.type='text';field.autocomplete='off';}field.name=key;field.value=row[key]??'';field.maxLength=8000;field.id='field-'+key;label.append(field);if(key==='pattern'){const hint=document.createElement('small');hint.textContent='Allowed slots: '+S.choices.templateSlots.map(x=>'{'+x+'}').join(' ');label.append(hint);}if(key.endsWith('_slots')||key.endsWith('_features')){const hint=document.createElement('small');hint.textContent='Separate values with |. Example: '+(key.endsWith('_slots')?'metric|entity|period':'ROOT|RWA');label.append(hint);}$('edit-fields').append(label);}$('edit-dialog').showModal();}
function removeRow(i){if(S.busy)return;if(!confirm(`Delete this rule from the draft?\n${Object.values(S.tables[S.file].rows[i]).slice(0,3).join(' · ')}\nThe CSV file will not change until you save.`))return;S.tables[S.file].rows.splice(i,1);mutate();render();}
$('edit-form').onsubmit=e=>{e.preventDefault();if(S.busy)return;const{file,index}=S.edit;const row=Object.fromEntries(S.tables[file].headers.map(k=>[k,$('edit-form').elements.namedItem(k).value]));if(index===null)S.tables[file].rows.push(row);else S.tables[file].rows[index]=row;$('edit-dialog').close();mutate();render();note('Applied to the browser draft. Validate and test questions before saving.');};
$('close-edit').onclick=$('cancel-edit').onclick=()=>$('edit-dialog').close();
function download(text,name,mime='text/plain;charset=utf-8'){const b=new Blob([text],{type:mime});const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function csvString(table){const esc=v=>/[",\n\r]/.test(v)?'"'+v.replaceAll('"','""')+'"':v;return '\ufeff'+[table.headers,...table.rows.map(r=>table.headers.map(k=>r[k]))].map(row=>row.map(esc).join(',')).join('\r\n')+'\r\n';}
async function validateDraft(){if(S.draft?.epoch===S.epoch)return S.draft;const epoch=S.epoch;note('Validating the draft with the existing Python compiler.');const data=await api('validate',{revision:S.base.revision,tables:S.tables});if(epoch!==S.epoch)throw Error('The draft changed during validation. Validate it again.');S.draft={...data,epoch};$('build-log').textContent=data.log+'\n\nChanged files:\n'+JSON.stringify(data.changes,null,2);$('build-status').textContent=`Validation passed · ${data.changes.length} file(s) changed · Artifact ${data.artifactHash.slice(0,12)}`;note('Validation passed. Test questions with the draft, or confirm and save the CSVs and generated file.');updateActions();return S.draft;}
async function withBusy(fn){if(S.busy)return;busy(true);try{return await fn();}catch(e){handleError(e);}finally{busy(false);}}
$('validate').onclick=()=>withBusy(validateDraft);
$('save').onclick=()=>withBusy(async()=>{const d=await validateDraft();const changes=d.changes.map(c=>`${c.file}: ${c.beforeRows} → ${c.afterRows} rows`).join('\n');if(!confirm(`Save to the local project?\n\n${changes||'No CSV changes · Revalidate the generated file'}\n\nExisting files will be backed up before updating the CSVs and command_patterns.txt. Nothing is automatically deployed to the bank website.`))return;const resp=await api('commit',{draftId:d.draftId,revision:S.base.revision,note:'Browser rule edit'});adopt(resp);$('build-status').textContent='Save complete · Source CSVs and command_patterns.txt updated.';note('Saved. Backup ID: '+resp.backupId+'\nTo update the web app, deploy the generated command_patterns.txt through your approved process and reload.');});
$('reload').onclick=()=>withBusy(async()=>{if(changedFiles().length&&!confirm('Discard unsaved drafts and reload the latest files from disk?'))return;adopt(await api('snapshot'));note('Loaded the latest files from disk.');});
$('download-artifact').onclick=()=>withBusy(async()=>{const r=await fetch('/api/download',{headers:{'X-RWA-CSRF':S.token},cache:'no-store'});if(!r.ok)throw Error('Could not download the generated file. Validate and save first.');download(await r.text(),'command_patterns.txt');});
$('add-row').onclick=()=>editRow();$('search').oninput=()=>{S.page=0;renderTable();};$('enabled-only').onchange=()=>{S.page=0;renderTable();};$('previous').onclick=()=>{S.page--;renderTable();};$('next').onclick=()=>{S.page++;renderTable();};
$('csv-import').onclick=()=>{if(!S.busy)$('csv-file').click();};$('csv-file').onchange=()=>withBusy(async()=>{const file=$('csv-file').files[0];if(!file)return;if(file.size>4_000_000)throw Error('CSV files must be 4 MB or smaller.');const name=S.file;const result=await api('import',{file:name,text:await file.text()});if(!confirm(`Replace the ${name} draft with ${result.table.rows.length} rows?\nThe source file is unchanged until validation and save.`))return;S.tables[name]=result.table;mutate();render();note('CSV imported into the draft. Compiler validation has not run yet.');$('csv-file').value='';});
$('csv-export').onclick=()=>download(csvString(S.tables[S.file]),S.file,'text/csv;charset=utf-8');
for(const n of ['edit','test','backup'])$('tab-'+n).onclick=()=>setTab(n);
function context(){return {selectedClientGroupId:$('test-group').value||null,selectedMonth:$('test-month').value||null};}
function ruleText(){return $('test-source').value==='saved'?{text:S.base.generatedText,hash:S.base.artifactHash}:S.draft?{text:S.draft.generatedText,hash:S.draft.artifactHash}:null;}
async function ensureLab(){if($('test-source').value==='draft')await validateDraft();const r=ruleText();if(!r?.text)throw Error('No rule file is available. Validate and save first.');S.lab.ensure(r.text,r.hash);return r;}
function renderParse(result){const el=$('parse-badge');el.textContent=result.ok?'ACCEPT · Valid analysis request':(result.code||result.status||'REJECT')+' · Not executed';el.className='result-title '+(result.ok?'accept':'reject');$('plan-grid').replaceChildren();if(result.ok){const p=result.plan;const fields={Action:p.action,Group:p.groups?.length?p.groups:p.group,'Group ID':p.groupId,'Comparison IDs':p.comparisonIds,Entity:p.entities?.length?p.entities:p.entity,LEID:p.entityId,Period:p.period,Metric:p.metric,'Top N':p.topN,'Excluded drivers':p.excludedDrivers,'Excluded groups':p.excludedGroups,'Excluded entities':p.excludedEntities,Threshold:p.condition};for(const[k,v]of Object.entries(fields)){if(v===null||v===undefined||Array.isArray(v)&&!v.length)continue;const d=document.createElement('div');d.className='plan-field';const label=document.createElement('span');label.textContent=k;const value=document.createElement('strong');value.textContent=typeof v==='object'?JSON.stringify(v):String(v);d.append(label,value);$('plan-grid').append(d);}}$('parse-message').textContent=result.message||result.plan?.scoreMeaning||'';$('explain').textContent=JSON.stringify(result,null,2);$('execute').disabled=!result.ok;$('sample-answer').hidden=true;renderConversation();}
function renderConversation(){const el=$('conversation');el.replaceChildren();for(const t of S.lab.history){const div=document.createElement('div');div.className='chat-turn';const q=document.createElement('b');q.textContent=t.query;const ans=document.createElement('span');ans.textContent=t.answer;div.append(q,ans);el.append(div);}$('test-state').textContent=JSON.stringify(S.lab.engine?.state||{},null,2);}
$('parse').onclick=()=>withBusy(async()=>{await ensureLab();const lines=$('question').value.trim().split(/\r?\n/).filter(Boolean);if(lines.length!==1)throw Error('Enter one question, or use “Run all lines as a sample conversation”.');renderParse(S.lab.parse(lines[0],context()));});
$('question').addEventListener('input',()=>{S.lab.pending=null;$('execute').disabled=true;});
$('execute').onclick=()=>{try{const result=S.lab.execute();$('execute').disabled=true;$('sample-answer').textContent=(result.ok?'SAMPLE RESULT\n':'NO SUCCESSFUL EXECUTION\n')+(result.answer||result.message||JSON.stringify(result));$('sample-answer').hidden=false;renderConversation();}catch(e){handleError(e);}};
$('sequence').onclick=()=>withBusy(async()=>{await ensureLab();const lines=$('question').value.trim().split(/\r?\n/).filter(Boolean);if(!lines.length||lines.length>30)throw Error('Enter 1–30 questions, one per line.');S.lab.engine.reset();S.lab.history=[];let succeeded=0;for(const q of lines){const result=S.lab.parse(q,context());renderParse(result);if(!result.ok)break;const out=S.lab.execute();renderConversation();$('sample-answer').textContent=out.answer||out.message;$('sample-answer').hidden=false;$('execute').disabled=true;if(!out.ok)break;succeeded++;await new Promise(r=>setTimeout(r,0));}note(`Executed ${succeeded}/${lines.length} turns using local data. Processing stopped at the first failure or missing-data result.`,succeeded===lines.length?'':'warn');});
function resetConversation(){S.lab.reset();$('execute').disabled=true;renderConversation();$('parse-badge').textContent='Run a new interpretation.';$('plan-grid').replaceChildren();$('sample-answer').hidden=true;}
$('new-conversation').onclick=resetConversation;$('test-source').onchange=resetConversation;$('test-group').onchange=resetConversation;$('test-month').onchange=resetConversation;
$('run-checks').onclick=()=>withBusy(async()=>{const r=await ensureLab();$('checks-result').textContent='Running checks…';const results=await S.lab.runChecks(r.text,r.hash,S.customChecks);$('checks-result').textContent=`${results.passed}/${results.total} PASS · ${results.failed} FAIL\n${results.testKind}\n\n`+results.rows.map(x=>`${x.pass?'PASS':'FAIL'}  ${x.id}  ${x.query}${x.errors.length?'\n  '+JSON.stringify(x.errors):''}`).join('\n');note(`Local regression checks: ${results.passed}/${results.total}. These results apply only to the tested examples.`,results.failed?'warn':'');});
$('import-checks').onclick=()=>$('checks-file').click();$('checks-file').onchange=async()=>{try{const f=$('checks-file').files[0];if(!f)return;if(f.size>3_000_000)throw Error('The test file is too large.');const x=JSON.parse(await f.text());if(!Array.isArray(x)||!x.length||x.length>1000)throw Error('A JSON array with 1–1,000 test cases is required.');S.customChecks=x;$('checks-result').textContent=`Imported ${x.length} custom checks. They have not run yet.`;}catch(e){handleError(e);}};
$('export-checks').onclick=()=>{if(!S.lab.lastChecks){note('Run the regression checks first.','warn');return;}download(JSON.stringify(S.lab.lastChecks,null,2),'rule_manager_test_results.json','application/json');};
function refreshTestData(){const groups=S.lab.groups();const old=$('test-group').value;$('test-group').replaceChildren();for(const g of groups)$('test-group').add(new Option(g.name+' ['+g.id+']',g.id));$('test-group').value=groups.some(g=>g.id===old)?old:groups.find(g=>g.name==='SAMSUNG GROUP')?.id||groups[0]?.id||'';$('dataset-label').textContent=S.lab.getData().label+` · ${S.lab.getData().rows.length.toLocaleString()} rows · USDm`;$('execute').disabled=true;renderConversation();}
$('test-data').onchange=()=>withBusy(async()=>{const f=$('test-data').files[0];if(!f)return;await S.lab.importData(f);refreshTestData();note('Data was read only in this browser tab. It was not uploaded to the Python server or saved in the CSV rules.');});
$('reset-data').onclick=()=>{S.lab.resetData();$('test-data').value='';refreshTestData();};
async function refreshBackups(){const {backups}=await api('backups');$('backup-list').replaceChildren();if(!backups.length){$('backup-list').textContent='No save history yet. A backup will be created before the first save.';return;}for(const b of backups){const card=document.createElement('div');card.className='backup-card';const info=document.createElement('div');const h=document.createElement('strong');h.textContent=new Date(b.createdAt).toLocaleString();const p=document.createElement('p');p.textContent=(b.note||'Save')+' · '+b.status;const small=document.createElement('small');small.textContent=b.id;info.append(h,p,small);const btn=document.createElement('button');btn.className='quiet';btn.textContent='Restore pre-save version';btn.onclick=()=>withBusy(async()=>{if(!confirm(`Restore the CSVs from before this save?\n${b.id}\nThe current draft will be discarded, and the current files on disk will be backed up.`))return;const r=await api('restore',{backupId:b.id,revision:S.base.revision});adopt(r);note('Backup CSVs validated, recompiled and restored.');await refreshBackups();});card.append(info,btn);$('backup-list').append(card);}}
$('refresh-backups').onclick=()=>withBusy(refreshBackups);
window.addEventListener('beforeunload',e=>{if(changedFiles().length){e.preventDefault();e.returnValue='';}});
async function init(){try{const r=await fetch('/api/bootstrap',{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.message);S.token=b.csrfToken;S.metadata=b.metadata;S.choices=b.choices;$('project-label').textContent=b.projectName+'\nManager '+b.managerVersion;adopt(b);S.lab.setAssets(await api('test-assets'));refreshTestData();note(b.recovery?'Interrupted save recovery: '+b.recovery.status:'Ready. Edit rules → Validate draft → Test questions → Save.');}catch(e){handleError(e);}}
init();
