import {TestLab} from './test_lab.js';
import {newLab,defaultContext,humanPlan,friendlyError,suggestion,proposeExamples,verifyDraft,FIELD_ACTIONS,interpretationMessage} from './simple_logic.js';
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
const S={token:'',base:null,cards:[],recipes:[],assets:null,lab:null,w:null,busy:false,lastQuery:'',lastParsed:null};
async function api(path,payload){const r=await fetch('/api/'+path,{method:payload?'POST':'GET',cache:'no-store',headers:{'X-RWA-CSRF':S.token,...(payload?{'Content-Type':'application/json'}:{})},...(payload?{body:JSON.stringify(payload)}:{})});const data=await r.json();if(!r.ok)throw data;return data;}
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function notice(id,text,bad=false){const e=$(id);e.hidden=!text;e.className='notice'+(bad?' error':'');e.replaceChildren();if(text)e.textContent=text;}
function showError(id,error){const f=friendlyError(error),e=$(id);e.hidden=false;e.className='notice error';e.replaceChildren(el('strong','',f.title),el('div','',f.body));if(f.suggestions?.length)e.append(el('div','helper',f.suggestions.join(' · ')));}
function busy(flag){S.busy=flag;for(const e of document.querySelectorAll('button'))if(!e.dataset.locked)e.disabled=flag;}
async function reload(){const bootstrap=await fetch('/api/bootstrap',{cache:'no-store'});S.base=await bootstrap.json();if(!bootstrap.ok)throw S.base;S.token=S.base.csrfToken;const x=await api('capabilities');S.cards=x.cards;S.recipes=x.recipes;S.defaultN=x.defaultNumber;S.maxN=x.maxNumber;S.assets=await api('test-assets');S.lab=newLab(S.assets,S.base.generatedText,S.base.artifactHash);const ctx=defaultContext(S.lab);const localGroups=S.lab.groups(),nameCounts=new Map();for(const g of localGroups)nameCounts.set(g.name,(nameCounts.get(g.name)||0)+1);$('test-group').replaceChildren(...localGroups.map(g=>new Option(g.name+(nameCounts.get(g.name)>1?' ['+g.id+']':''),g.id)));$('test-group').value=ctx.selectedClientGroupId;$('test-month').value=ctx.selectedMonth;$('project-name').textContent=S.base.projectName;renderCards();if(!S.base.artifactConsistent)notice('notice','The source files and generated rules differ. Use Advanced to validate and rebuild before editing.',true);}
function renderCards(){const term=$('search').value.trim().toLowerCase(),cards=S.cards.filter(c=>(c.title+' '+c.examples.join(' ')).toLowerCase().includes(term));$('capability-list').replaceChildren();for(const c of cards){const a=el('article','capability');a.dataset.capabilityId=c.id;const type=el('div','card-category');type.append(el('i'),document.createTextNode(c.group));a.append(type,el('h3','',c.title));const example=el('p','example');example.append(el('span','','Example'),document.createTextNode('“'+(c.examples[0]||'Add an example question')+'”'));a.append(example);const actions=el('div','card-actions'),edit=el('button','edit-button','Edit'),del=el('button','delete-button','Delete');edit.onclick=()=>openWizard(c);del.onclick=()=>deleteCard(c);actions.append(edit,del,el('span','card-badge',c.needsReview?'Needs review':c.builtin?'Built-in report':'Your capability'));a.append(actions);$('capability-list').append(a);}$('empty-search').hidden=!!cards.length;$('cap-count').textContent=cards.length+(term?' matches':' available');}
$('search').oninput=renderCards;$('add-capability').onclick=()=>openWizard();
$('test-engine').onclick=()=>{$('home').hidden=true;$('test-page').hidden=false;window.scrollTo(0,0);$('test-question').focus();};$('back-home').onclick=()=>{$('home').hidden=false;$('test-page').hidden=true;};
function context(){return {selectedClientGroupId:$('test-group').value||undefined,selectedMonth:$('test-month').value||undefined};}
function renderMeaning(target,result,query){const dl=$(target);dl.replaceChildren();for(const[k,v]of humanPlan(result,query))dl.append(el('dt','',k),el('dd','',v));}
async function testQuestion(){const q=$('test-question').value.trim();if(!q){notice('test-notice','Enter one question to test.',true);return;}notice('test-notice','');try{const r=S.lab.parse(q,context());S.lastQuery=q;S.lastParsed=r;$('test-result').hidden=false;$('result-title').textContent=r.ok?'✓ Understood':'Let’s make this clearer.';$('result-title').classList.toggle('rejected',!r.ok);renderMeaning('meaning-grid',r,q);$('result-message').textContent=interpretationMessage(r);$('looks-right').disabled=!r.ok;$('looks-right').hidden=!r.ok;$('fix-interpretation').disabled=false;}catch(e){showError('test-notice',e);}}
$('check-question').onclick=testQuestion;$('test-question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();testQuestion();}};
$('test-question').oninput=()=>{S.lab.pending=null;$('test-result').hidden=true;};
$('looks-right').onclick=()=>{try{const r=S.lab.execute();if(!r.ok)throw {message:r.answer||'Local sample calculation failed.'};notice('test-notice','Meaning confirmed. You can now ask a follow-up. No rules were changed.');const d=el('details'),s=el('summary','',S.lastQuery),p=el('pre','',r.answer);d.append(s,p);$('conversation-log').append(d);$('looks-right').disabled=true;$('test-question').value='';$('test-question').focus();}catch(e){showError('test-notice',e);}};
$('reset-conversation').onclick=()=>{S.lab.reset();S.lab.ensure(S.base.generatedText,S.base.artifactHash);$('test-result').hidden=true;$('conversation-log').replaceChildren();notice('test-notice','Conversation cleared.');};for(const id of ['test-group','test-month'])$(id).onchange=()=>$('reset-conversation').click();
$('fix-interpretation').onclick=()=>openWizard(null,{query:S.lastQuery,parsed:S.lastParsed});
function openWizard(card=null,fix=null){
 S.w={step:1,id:card?.id||null,builtin:!!card?.builtin,title:card?.title||'',kind:card?.kind||'',measure:card?.measure||'increase',numberMode:card?.numberMode||'question',exampleNumber:card?.exampleNumber||10,periodMode:card?.periodMode||'question',examples:card?.examples?.slice()||[fix?.query||''],bindings:card?.bindings||[],fix:!!fix,fixQuery:fix?.query||'',draft:null,checks:null};
 if(fix?.parsed?.plan){const r=S.recipes.find(r=>r.command===fix.parsed.plan.action);if(r)S.w.kind=r.key;}
 $('wizard-mode').textContent=fix?'FIX INTERPRETATION':card?'EDIT CAPABILITY':'ADD CAPABILITY';renderStep();$('wizard').showModal();
}
function closeWizard(){if(S.busy)return;if(S.w?.step>1&&!confirm('Discard this unsaved change? Your saved rules will stay the same.'))return;$('wizard').close();S.w=null;}
$('close-wizard').onclick=closeWizard;$('wizard').oncancel=e=>{e.preventDefault();closeWizard();};
function detailsLabel(label,node){const d=el('div','detail-field'),l=el('label','',label);l.htmlFor=node.id;d.append(l,node);return d;}
function select(id,items,value,fn){const s=el('select');s.id=id;for(const[k,t]of items)s.add(new Option(t,k));s.value=value;s.onchange=()=>fn(s.value);return s;}
function titleFor(recipe,w){if(recipe?.detail==='ranking'){const measure={increase:'RWA increase',decrease:'RWA decrease',highest:'total RWA',lowest:'lowest RWA',percentage:'percentage increase',question:'RWA movement'}[w.measure];return (recipe.key==='rank_groups'?'Top groups':'Top entities')+' by '+measure;}return recipe?.title||'New capability';}
const titles=['What should the engine understand?','What does this mean?','A few details.','How else might someone ask?','Ready to save?'];
const descriptions=['Start with one question someone would actually type.','Choose an existing report. We will connect the wording for you.','Only the options relevant to your report appear here.','Add natural examples. Names, numbers and dates are still read from each question.','Check the meaning. We check your examples and protect the working rules before saving.'];
function renderStep(){
 const w=S.w;notice('wizard-error','');$('wizard-content').replaceChildren();$('wizard-title').textContent=titles[w.step-1];$('wizard-description').textContent=descriptions[w.step-1];$('step-label').textContent='Step '+w.step+' of 5';$('wizard-progress').replaceChildren(...Array.from({length:5},(_,i)=>el('span',i<w.step?'done':'')));$('wizard-back').hidden=w.step===1;$('wizard-next').textContent=w.step===5?'Save capability':'Continue →';$('wizard-next').disabled=w.step===5;$('wizard-saving').textContent='';const box=$('wizard-content');
 if(w.step===1){const label=el('label','field-label','Example question');label.htmlFor='representative';const input=el('textarea','large-input');input.id='representative';input.rows=4;input.placeholder='Show me the top 10 groups with the biggest RWA increase';input.value=w.examples[0]||'';input.oninput=()=>{w.examples[0]=input.value;w.draft=null;};box.append(label,input,el('p','helper','Example: “Show me the top 10 groups with the biggest RWA increase”'));const opt=el('details','optional-name'),sum=el('summary','','Name this capability (optional)'),name=el('input');name.id='capability-title';name.value=w.title;name.placeholder='We will suggest a clear name';name.maxLength=140;name.oninput=()=>w.title=name.value;opt.append(sum,name);box.append(opt);setTimeout(()=>input.focus(),50);}
 if(w.step===2){
  const primaryKeys=['rank_groups','rank_entities','movement','compare_periods','history','reconcile'];let recipes=S.recipes;
  if(w.builtin){const own=recipes.find(r=>r.key===w.kind);recipes=recipes.filter(r=>r.command===own?.command&&!!r.command||r.key===own?.key);}
  const make=(rs)=>{const grid=el('div','choice-grid');for(const r of rs){const l=el('label','choice'+(w.kind===r.key?' selected':'')),radio=el('input');radio.type='radio';radio.name='report-kind';radio.value=r.key;radio.checked=w.kind===r.key;radio.onchange=()=>{w.kind=r.key;w.draft=null;if(r.detail!=='ranking'&&r.detail!=='movement')w.measure='question';else if(w.measure==='question')w.measure='increase';w.periodMode='question';renderStep();};const txt=el('span','',r.title);l.append(radio,txt);grid.append(l);}return grid;};
  const first=recipes.filter(r=>primaryKeys.includes(r.key)),more=recipes.filter(r=>!primaryKeys.includes(r.key));box.append(make(first.length?first:recipes));if(first.length&&more.length){const det=el('details','more-options');det.open=more.some(r=>r.key===w.kind);det.append(el('summary','','More supported reports & follow-ups'),make(more));box.append(det);}
  if(w.fix){const matches=S.cards.filter(c=>c.kind===w.kind);const choices=[['','Create a separate capability'],...matches.map(c=>[c.id,'Add to: '+c.title])];const chooser=select('fix-target',choices,w.id||'',id=>{const c=S.cards.find(c=>c.id===id);w.id=id||null;w.builtin=!!c?.builtin;w.bindings=c?.bindings||[];w.title=c?.title||'';w.examples=c?[...c.examples.filter(q=>q!==w.fixQuery),w.fixQuery]:[w.fixQuery];if(c){w.measure=c.measure;w.numberMode=c.numberMode;w.exampleNumber=c.exampleNumber;w.periodMode=c.periodMode;}});box.append(detailsLabel('Where should this expression belong?',chooser));}
 }
 if(w.step===3){const r=S.recipes.find(r=>r.key===w.kind);if(!r)return;
  if(r.detail==='ranking'||r.detail==='movement'){
    const measures=r.detail==='ranking'?[['increase','Biggest RWA increase'],['decrease','Biggest RWA decrease'],['highest','Highest total RWA'],['lowest','Lowest total RWA'],['percentage','Biggest percentage increase'],['question','As stated in the question']]:[['increase','RWA increase'],['decrease','RWA decrease'],['question','As stated in the question']];
    box.append(detailsLabel(r.detail==='ranking'?'Rank by':'Explain',select('measure',measures,w.measure,v=>{w.measure=v;})));
  }
  if(r.detail==='ranking'){
    box.append(detailsLabel('How many results?',select('number-mode',[['question','Use the number in the question'],['default','Use the engine default ('+S.defaultN+')']],w.numberMode,v=>{w.numberMode=v;$('example-number-field').hidden=v==='default';})));
    const number=el('input');number.id='example-number';number.type='number';number.min='1';number.max=String(S.maxN);number.value=w.exampleNumber;number.oninput=()=>w.exampleNumber=Number(number.value);const field=detailsLabel('Number used in the suggested example',number);field.id='example-number-field';field.hidden=w.numberMode==='default';box.append(field);
  }
  if(!r.patch&&r.detail!=='compare')box.append(detailsLabel('Period in your examples',select('period-mode',[['question','Read the period from the question'],['context','Use the current analysis context'],['current','Explicitly ask for this month'],['previous','Explicitly ask for last month'],['last3','Explicitly ask for the last 3 months']],w.periodMode,v=>w.periodMode=v)));
  if(r.patch)box.append(el('div','suggestion','This continues the last successful report. Only the requested group, period, driver or filter is changed. Previous result amounts are never copied.'));
  if(r.detail==='compare')box.append(el('div','suggestion',r.key==='compare_periods'?'Each example must name two reporting periods. The engine will compare them for the chosen client group.':'Each example must name two client groups. Existing period and data checks still apply.'));
  if(r.detail==='ranking')box.append(el('p','helper','The default number is shared by the engine. This wizard does not silently change other reports. Use explicit wording to set a different number or period.'));
 }
 if(w.step===4){const r=S.recipes.find(r=>r.key===w.kind);const list=el('div');list.id='example-list';box.append(list);
  function renderExamples(){list.replaceChildren();w.examples.forEach((q,i)=>{const row=el('div','example-row'),label=el('label','','Example '+(i+1));const a=el('textarea');a.rows=2;a.value=q;a.maxLength=1000;a.setAttribute('aria-label','Example '+(i+1));a.oninput=()=>{w.examples[i]=a.value;w.draft=null;};row.append(label,a);if(w.examples.length>1){const del=el('button','text-button','Remove example');del.onclick=()=>{w.examples.splice(i,1);renderExamples();};row.append(del);}list.append(row);});}
  renderExamples();const add=el('button','button secondary','+ Add another example');add.onclick=()=>{if(w.examples.length>=20)return;w.examples.push('');renderExamples();list.lastElementChild.querySelector('textarea').focus();};box.append(add);
  const hint=el('div','suggestion'),sample=suggestion(r,w);hint.append(el('strong','','Suggested wording for these choices'),el('div','',sample));const use=el('button','text-button','Use this as the first example');use.onclick=()=>{w.examples[0]=sample;w.draft=null;renderExamples();};hint.append(use);box.append(hint);
 }
 if(w.step===5){box.append(el('h3','',w.title||titleFor(S.recipes.find(r=>r.key===w.kind),w)));const grid=el('dl','meaning-grid');grid.id='review-meaning';box.append(grid);const list=el('ul','review-examples');for(const q of w.examples)list.append(el('li','','“'+q+'”'));box.append(list);const progress=el('div','check-status');progress.id='review-check-status';progress.append(el('span','spinner'),el('span','','Validating the change and checking examples…'));box.append(progress);box.append(el('p','helper','New wording is linked to existing reports. Shared expressions are preserved. No learning, new calculation, or automatic deployment.'));prepareReview();}
}
// Deliberately tiny state machine: no separate forms for Add, Edit or Fix.
$('wizard-back').onclick=()=>{if(S.busy)return;if(S.w.step>1){S.w.step--;renderStep();}};
$('wizard-next').onclick=async()=>{
 const w=S.w;if(S.busy)return;
 if(w.step===5){await saveWizard();return;}
 if(w.step===1&&!w.examples[0]?.trim()){notice('wizard-error','Enter one example question to continue.',true);return;}
 if(w.step===2&&!w.kind){notice('wizard-error','Choose the report you mean.',true);return;}
 if(w.step===3&&(!Number.isInteger(w.exampleNumber)||w.exampleNumber<1||w.exampleNumber>S.maxN)){notice('wizard-error','Use an example number between 1 and '+S.maxN+'.',true);return;}
 if(w.step===4){w.examples=w.examples.map(q=>q.trim()).filter(Boolean);if(!w.examples.length){notice('wizard-error','Add at least one example.',true);return;}}
 w.step++;renderStep();
};
async function prepareReview(){
 const w=S.w,recipe=S.recipes.find(r=>r.key===w.kind);busy(true);$('wizard-saving').textContent='Checking · no files changed';
 try{
  const lab=newLab(S.assets,S.base.generatedText,S.base.artifactHash),ctx=context(),examples=proposeExamples(lab,recipe,w,w.examples,ctx,w.bindings);
  const draft=await api('capabilities/prepare',{revision:S.base.revision,operation:'save',id:w.id,title:w.title||titleFor(recipe,w),kind:w.kind,measure:w.measure,numberMode:w.numberMode,exampleNumber:w.exampleNumber,periodMode:w.periodMode,examples});draft.recipes=S.recipes;
  const checks=await verifyDraft(S.assets,S.base,draft,recipe,w,w.examples,ctx,n=>{$('wizard-saving').textContent='Checking existing questions… '+n;});
  w.draft=draft;w.checks=checks;
  if(checks.failed.length)throw {code:'MEANING_MISMATCH',message:checks.failed[0].message+' Example: “'+checks.failed[0].query+'”'};
  const first=checks.checks.find(c=>c.name==='Example');const dl=$('review-meaning');dl.replaceChildren();for(const[k,v]of first?.meaning||[])dl.append(el('dt','',k),el('dd','',v));
  $('review-check-status').replaceChildren(el('strong','','✓ '+checks.total+' interpretation checks passed'));
  $('wizard-saving').textContent='Ready to save';
 }catch(e){w.draft=null;showError('wizard-error',e);$('review-check-status')?.replaceChildren(el('span','','The current working rules have not been changed.'));$('wizard-saving').textContent='Please revise the examples';
  const actions=el('div','error-actions'),edit=el('button','button secondary','Edit examples'),suggested=el('button','text-button','Use suggested wording');
  edit.onclick=()=>{w.step=4;renderStep();};suggested.onclick=()=>{w.examples[0]=suggestion(recipe,w);w.step=4;renderStep();};actions.append(edit,suggested);$('wizard-error').append(actions);}
 finally{busy(false);$('wizard-next').disabled=!w.draft;}
}
async function saveWizard(){const w=S.w;if(!w.draft||!w.checks||w.checks.failed.length)return;busy(true);try{await api('capabilities/commit',{draftId:w.draft.draftId,revision:S.base.revision,artifactHash:w.draft.artifactHash,checkToken:w.draft.checkToken,checksPassed:true});$('wizard').close();S.w=null;await reload();$('home').hidden=false;$('test-page').hidden=true;notice('notice','“'+w.draft.title+'” saved. Your CSV rules and generated file have been updated. Other shared expressions were preserved.');}catch(e){showError('wizard-error',e);}finally{busy(false);}}
let deleting=null;
function deleteCard(c){deleting=c;$('delete-title').textContent='Delete “'+c.title+'”?';$('delete-description').textContent=c.builtin?'This removes the capability. Shared words are preserved. If another capability uses the same report, that shared report will stay available.':'Only this saved capability and unused expressions created for it will be removed. Shared expressions stay available.';notice('delete-notice','');$('delete-dialog').showModal();}
$('cancel-delete').onclick=()=>$('delete-dialog').close();$('delete-dialog').oncancel=e=>{if(S.busy)e.preventDefault();};
$('confirm-delete').onclick=async()=>{if(!deleting||S.busy)return;busy(true);const c=deleting;try{notice('delete-notice','Checking shared expressions and compiling the updated rules…');const d=await api('capabilities/prepare',{revision:S.base.revision,operation:'delete',id:c.id});d.recipes=S.recipes;const r=S.recipes.find(r=>r.key===c.kind);const checks=await verifyDraft(S.assets,S.base,d,r,c,[],context());if(checks.failed.length)throw {message:checks.failed[0].message};await api('capabilities/commit',{draftId:d.draftId,revision:S.base.revision,artifactHash:d.artifactHash,checkToken:d.checkToken,checksPassed:true});$('delete-dialog').close();await reload();notice('notice','“'+c.title+'” deleted. '+(d.notices.join(' ')||'Shared expressions were preserved.'));}catch(e){showError('delete-notice',e);}finally{busy(false);}};
$('download-rules').onclick=async()=>{try{const r=await fetch('/api/download',{headers:{'X-RWA-CSRF':S.token},cache:'no-store'});if(!r.ok)throw await r.json();const blob=await r.blob(),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='command_patterns.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){showError('notice',e);}};
window.addEventListener('beforeunload',e=>{if(S.w){e.preventDefault();e.returnValue='';}});
(async()=>{busy(true);try{await reload();}catch(e){showError('notice',e);}finally{busy(false);}})();
